err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
322 INFO: PyInstaller: 3.3.1
330 INFO: PyInstaller: 3.3.1
330 INFO: Python: 3.4.4
331 INFO: Platform: Windows-XP-5.1.2600-SP3
332 INFO: wrote Z:\p2e\4.spec
328 INFO: Python: 3.4.4
328 INFO: Platform: Windows-XP-5.1.2600-SP3
329 INFO: wrote Z:\p2e\script.spec
346 INFO: UPX is not available.
347 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
341 INFO: UPX is not available.
343 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
361 INFO: Extending PYTHONPATH with paths
['Z:\\p2e\\workingdir\\1516458409191', 'Z:\\p2e']
362 INFO: checking Analysis
362 INFO: Building Analysis because out00-Analysis.toc is non existent
362 INFO: Initializing module dependency graph...
Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "c:\Python34\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 687, in build
    shutil.rmtree(f)
  File "c:\Python34\lib\shutil.py", line 482, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\Python34\lib\shutil.py", line 377, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\Python34\lib\shutil.py", line 375, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 2] File not found: 'C:\\users\\root\\Application Data\\pyinstaller\\bincache00_py34_32bit\\_bz2.pyd'
382 INFO: Initializing module graph hooks...
392 INFO: Analyzing base_library.zip ...
