err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
142 INFO: PyInstaller: 3.3.1
143 INFO: Python: 3.4.4
143 INFO: Platform: Windows-XP-5.1.2600-SP3
147 INFO: wrote Z:\p2e\ssss.spec
153 INFO: UPX is not available.
154 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
166 INFO: Extending PYTHONPATH with paths
['Z:\\p2e\\workingdir\\1516561608389',
 'Z:\\p2e\\workingdir\\1516561608389\\additionalmodules',
 'Z:\\p2e']
167 INFO: checking Analysis
167 INFO: Building Analysis because out00-Analysis.toc is non existent
167 INFO: Initializing module dependency graph...
176 INFO: Initializing module graph hooks...
180 INFO: Analyzing base_library.zip ...
6784 INFO: Processing pre-find module path hook   distutils
10258 INFO: running Analysis out00-Analysis.toc
10772 INFO: Caching module hooks...
10786 INFO: Analyzing Z:\p2e\workingdir\1516561608389\ssss.py
11836 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
16214 INFO: Loading module hooks...
16215 INFO: Loading module hook "hook-encodings.py"...
16398 INFO: Loading module hook "hook-distutils.py"...
16401 INFO: Loading module hook "hook-certifi.py"...
16406 INFO: Loading module hook "hook-pydoc.py"...
16407 INFO: Loading module hook "hook-xml.py"...
16615 INFO: Loading module hook "hook-requests.py"...
16661 INFO: Looking for ctypes DLLs
16736 INFO: Analyzing run-time hooks ...
16753 INFO: Looking for dynamic libraries
17042 INFO: Looking for eggs
17042 INFO: Using Python library c:\Python34\python34.dll
17042 INFO: Found binding redirects: 
[]
17051 INFO: Warnings written to ./workingdir/1516561608389/build/ssss\warnssss.txt
17240 INFO: Graph cross-reference written to ./workingdir/1516561608389/build/ssss\xref-ssss.html
17302 INFO: Appending 'datas' from .spec
17306 INFO: checking PYZ
17307 INFO: Building PYZ because out00-PYZ.toc is non existent
17307 INFO: Building PYZ (ZlibArchive) ./workingdir/1516561608389/build/ssss\out00-PYZ.pyz
19526 INFO: Building PYZ (ZlibArchive) ./workingdir/1516561608389/build/ssss\out00-PYZ.pyz completed successfully.
19586 INFO: checking PKG
19586 INFO: Building PKG because out00-PKG.toc is non existent
19586 INFO: Building PKG (CArchive) out00-PKG.pkg
19603 INFO: Updating manifest in C:\users\root\Application Data\pyinstaller\bincache00_py34_32bit\python34.dll
19604 INFO: Updating resource type 24 name 2 language 1033
21943 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
21956 INFO: Bootloader c:\Python34\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
21957 INFO: checking EXE
21957 INFO: Building EXE because out00-EXE.toc is non existent
21957 INFO: Building EXE from out00-EXE.toc
21960 INFO: SRCPATH [('workingdir\\1516561608389\\additionalicon\\a.ico', None)]
21961 INFO: Updating icons from ['workingdir\\1516561608389\\additionalicon\\a.ico'] to C:\users\root\Temp\tmpus9im1dk
Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "c:\Python34\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "c:\Python34\lib\site-packages\PyInstaller\building\api.py", line 420, in __init__
    self.__postinit__()
  File "c:\Python34\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\Python34\lib\site-packages\PyInstaller\building\api.py", line 509, in assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "c:\Python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 166, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "c:\Python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 123, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "c:\Python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 95, in __init__
    entry.fromfile(file)
  File "c:\Python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 65, in fromfile
    self._fields_ = list(struct.unpack(self._format_, data))
struct.error: unpack requires a bytes object of length 16
